### ISSUE TITLE
老哥能解决一下小白的问题吗

### ISSUE THREAD

**Issue by cnmmpbnq** [sa1utyeggs/cnki-anisys_all-crawler#2]
就是开始爬取知网内容的时候经常出现 这种指针异常，不知道为什么，可以的话帮我答疑一下好吗，我的email 2093397813@qq.com
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.hh.Main.getPaperDetailKey(Main.java:253)
	at com.hh.Main.insertPaperInfo(Main.java:39)
	at com.hh.Main.main(Main.java:33)

**Comment by sa1utyeggs** [comment]
抱歉，我没想到有人会拿去用，麻烦你能具体点描述描述问题吗？
由于.insertPaperInfo方法是将数据爬取之后，插入数据库的。有可能是这里错的；
你要是想测试的话，可以将.insertPaperInfo方法中插入数据库的代码删除

**Comment by cnmmpbnq** [comment]
后面使用可以正常插入数据库的，就有的时候运行会直接报错(不清楚原因)，然后就等待几分钟或者更久
就能正常使用了，最近也是在写论文当中，所以想爬一些相关性的看看，
很不错的开源，谢谢老哥，谢谢，谢谢！
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sa1utyeggs/cnki-anisys_all-crawler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 中午12:24
***@***.***&gt;;
抄送:&nbsp;"Look at ***@***.******@***.***&gt;;
主题:&nbsp;Re: [sa1utyeggs/cnki-anisys_all-crawler] 老哥能解决一下小白的问题吗 (Issue #2)





 
抱歉，我没想到有人会拿去用，麻烦你能具体点描述描述问题吗？
 由于.insertPaperInfo方法是将数据爬取之后，插入数据库的。有可能是这里错的；
 你要是想测试的话，可以将.insertPaperInfo方法中插入数据库的代码删除

**Comment by sa1utyeggs** [comment]
你把数据库的IP改了吗，不会插入到我的数据库里了吧：）

**Comment by cnmmpbnq** [comment]
> 你把数据库的IP改了，不会插入到我的数据库里吧：）

哈哈哈哈，改了的连接我自己的，不然一开始就报错，而且用户名密码什么的都是‘’ * ‘’，连接不到你的~~~

**Comment by sa1utyeggs** [comment]
我知道问题出在哪了，我这个爬虫为了我项目使用方便，使用了两个参数；
我没有想到可能出现搜索结果为空的现象；
你可以看我最新提交的代码
