### ISSUE TITLE
sql

### ISSUE THREAD

**Issue by Hsgay** [sa1utyeggs/cnki-anisys_all-crawler#3]
有 建表语句嘛 大佬

**Comment by sa1utyeggs** [comment]
嗯。。插入数据库其实是非必要操作，你可以将数据库相关的代码注释；
如果你真的需要的话可以使用：
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for paper_info
-- ----------------------------
DROP TABLE IF EXISTS `paper_info`;
CREATE TABLE `paper_info`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `metabolite` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '代谢物',
  `disease` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '疾病',
  `title` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '题目',
  `url` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '访问url',
  `abstractText` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '摘要',
  `mainSentence` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '主要判断的句子',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `disease_idx`(`disease`) USING BTREE COMMENT '疾病名的索引',
  INDEX `metabolite_idx`(`metabolite`) USING BTREE COMMENT '代谢物的索引'
) ENGINE = InnoDB AUTO_INCREMENT = 1426 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;

**Comment by Hsgay** [comment]
好的 我试一试


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sa1utyeggs/cnki-anisys_all-crawler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月30日(星期三) 中午11:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sa1utyeggs/cnki-anisys_all-crawler] sql (Issue #3)





 
嗯。。插入数据库其实是非必要操作，你可以将数据库相关的代码注释；
 如果你真的需要的话可以使用：
 SET NAMES utf8mb4;
 SET FOREIGN_KEY_CHECKS = 0;
 
 
-- Table structure for paper_info
 
 
DROP TABLE IF EXISTS paper_info;
 CREATE TABLE paper_info  (
 id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
 metabolite varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '代谢物',
 disease varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '疾病',
 title varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '题目',
 url varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '访问url',
 abstractText text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '摘要',
 mainSentence text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '主要判断的句子',
 PRIMARY KEY (id) USING BTREE,
 INDEX disease_idx(disease) USING BTREE COMMENT '疾病名的索引',
 INDEX metabolite_idx(metabolite) USING BTREE COMMENT '代谢物的索引'
 ) ENGINE = InnoDB AUTO_INCREMENT = 1426 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;
 
SET FOREIGN_KEY_CHECKS = 1;
